---
title: "Personal Science Guide to the Microbiome"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [psm-refs.bib]
biblio-style: apalike
link-citations: yes
description: "An introduction to Personal Science and uncovering the secrets of your own microbiome."
---


# Intro {-}

Science is about curiosity, a passion for truth, and a never-ending process of systematic experimentation in pursuit of an understanding of the world around us.  It's open to everyone and can be applied to any situation, including situations that affect you right now.  It's _Personal Science_ when you use the scientific method to discover important insights about the wellness and performance of yourself and those around you. 

This book will introduce you to one exciting area of personal science: understanding your own microbiome. Our [companion web site](https://app.personalscience.com) lets you upload your own data and compare it to others to make your own discoveries.

# What is Personal Science? 

When you’re sick with a chronic disease, and you’re willing to try anything to feel better, one of the struggles is simply knowing the level of severity. What is the precise version or name of this disease? What makes me different from a healthy person, or from the healthy person I used to be? Are there other people with the same condition, and if so, how does my situation compare to theirs? Am I getting better or worse?

Note that these are all questions about *context*. A first step in approaching your situation is to simply understand how you compare…how you compare to healthy people, to those who have the same condition as you do, to people who have partially or fully recovered.

Even symptom tracking is just one aspect of the question of context. I want to know more precisely the conditions under which my problem gets better or worse. In other words, what is the *context*? (e.g. are my migraines triggered by high altitudes, by caffeine, by stress, by something else? All of these are just other ways of saying “context”).

One simple example: if I wake up in the morning with a headache, or if I feel nauseous, my attitude — my response — will depend on which of the following is true:

1.  I drank lots of alcohol the night before

2.  I ate raw seafood from a street vendor.

3.  Someone in my family felt like this a few days ago.

4.  I was bitten by a tick last Summer and underwent a course of antibiotics that supposedly cleared it up — at least that’s what the test said.

5.  I’m a 90-year-old bedridden man on lots of medications

These examples are of course extreme — we intuitively understand that a diagnosis depends on the cause behind the symptoms — but even when the cause is known, our treatment options will be guided by *context*, by reference values.

## Reference Values

Much of our understanding of context is driven by reference values. A doctor knows whether your cholesterol is high or low based on large population studies of other people. Every health study is essentially just a way to calculate reference values: of the n people exposed to this treatment, some fraction will improve. If that fraction is large enough, we say the treatment works. If not, the treatment doesn’t work.

So the real question in any medical condition is: what is the reference value? What is the standard by which I am judging my current condition?

For many (most) situations, the reference values have been pre-computed based the medical community’s long experience treating patients like you. We know that X% of people with your type of cancer respond well to this drug. We know that Y% of people who smoke develop this disease. And on and on.

But for some situations, there is no reference value. The microbiome, for example. Nobody knows what “healthy” is, in general. We need more data before we can say definitively that such-and-such abundance levels are “healthy” or “unhealthy”.

In other cases, there are reference values for the general population, but not necessarily for you. The average height of a 3-year-old girl, for example, is based on data from umpteen thousands of 3-year-olds, but what about among 3-year-olds of your ethnic group, or your family, or people of your socio-economic class, or those in your neighborhood? Whether to consider *your* 3-year-old for special treatment depends entirely on which reference group you are using.

How can we get those reference values?

In other cases, a treatment may be too new, or too crazy, for there to be reference values. A terminal cancer patient who tries an experimental treatment, for example, is living in a world of unknown reference values. Importantly, after they try the treatment, they become one of the reference values. And that’s great! we now have a reference value for that treatment — but only if somebody bothers to record it. Often that data simply falls on the floor with nobody to catch it.

## Quantifying the anecdotal

If the results of a treatment are not recorded, we still have reference values. People still rely on word of mouth — anecdotes — when looking for new treatments. But those reference values are anecdotal. You regularly hear stories of the form “I tried X and it worked for me”. Hear enough of those stories and you may want to try it yourself. But how many of those stories constitutes “enough” to try for yourself?

What if there were a common way for everyone who tries X to record their results quantitatively?

That’s the idea behind symptom tracking, and it’s a nice start. Some companies try to add fancy additional features on top, like using machine learning to try to guess better than you can alone about the various correlations found within your data. Getwell.ai or Doc.Ai go this direction — gather enough data, either from yourself or from others, so that we can predict the causes for various states. Again, that’s interesting and it’s a nice start, but it’s limited.

What you really want — and the key, original idea behind Personal Science — is to let you take that quantitative data and *compare* it to others: others like you, people who you consider to be just like you except for such-and-such symptom.

Now, in some cases, a symptom tracking or quantified self product will let you see yourself compared to *an aggregated* summary of all other users. Fitbit might let you compare yourself to all those of your sex or age, for example, or maybe those in your geography. This is a good start.

But what if you could choose your own subset of users with whom you want to compare yourself? Because only *you* know which type of person you identify with, or to which type of health condition you want to belong, Personal Science lets you analyze and study the data as a whole.

That’s why it’s *personal* -- it’s about the one, unique data point that is you -- and why it’s *science* -- democratize the quantitative tools of science to let you understand your condition, for yourself.


Most of the examples are based on over 600 near-daily samples I took of my own microbiome over a three year period. Inspired by an experiment conducted at MIT^[@david_host_2014], during most of that time I also carefully tracked the food I ate, my sleep, and other variables like activity or location. Most of my near-daily samples were of my gut, but I also regularly tested my skin, nose, and mouth. Since I’m generally healthy, I didn’t have a specific goal in mind other than to try to understand better what these microbes are doing, so many of my tests were taken while undergoing simple experiments, like eating a specific type of food or visiting a new location. While not necessarily up to the rigorous standards of a formal scientific trial, these “n of 1” studies on myself helped me discover several new interesting facts about my own microbiome, many of which appear to contradict other published studies. In addition, hundreds of people sent me their own test results, letting me compare many different microbiomes. And of course, I also followed the latest developments in scientific publications and the general press as I eagerly tried to learn more.

This book tells you what I learned.


```{r loadAllData, echo=FALSE, warning = FALSE, message = FALSE}

knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)

source("R/loadMHGData.R")


library(ggthemes)
theme_set( theme_light(base_family = "MarkPro"))
theme_set(theme_economist())# + scale_colour_economist())

if(Sys.info()["sysname"]=="Darwin"){
  quartzFonts(Candara = quartzFont(rep("Candara",4)), MarkPro = quartzFont(rep("MarkPro",4)))
} else windowsFonts(Candara = windowsFont("Candara"), MarkPro = windowsFont("MarkPro"))


```
