
### Hygiene** {#microbesHygiene}

Now for some speculation. I can't prove any of this, but these are some questions possibly worth asking:

What does (underarm) deoderant do?  Although rich people soaked themselves with various colognes for thousands of years, the widespread use of deoderant is less than 100 years old. 

Why do you have sweat glands there in the first place? Sweat is supposed to help cool your body, but not much cooling will happen from a surface that's not exposed to much air. Instead, those glands feed bacteria, 

Similar to the way some people do fecal transplants to modify their gut bacteria, someday it may be possible to do [arm pit bacteria transplants](https://www.fastcompany.com/3066047/armpit-bacteria-transplants-could-end-your-body-odor).

How often should you brush your teeth?

*Washing your hands in a public restroom*

In Westernized countries for the past hundred years, it's been taken for granted that everyone should wash their hands every time they use the toilet, especially in a public place. Washing with soap and water, of course, is an effective way to remove harmful microbes, but I wonder what happens to your hands _after_ washing, when you turn off the faucet or help yourself to the paper towel machine. Even in a restroom with those fancy automatic on/off devices, you still probably touch the doorknob on your way out.

We know that fecal matter often harbors pathogenic microbes, and of course the act of doing your business makes it likely that your hands will come closer to unpleasant waste products, but I wonder: most of the microbes you're touching are already on your body. I suspect that microbes optimised for some parts of your body won't do well on the hands anyway. But meanwhile, that faucet is being handled all day by crowds of strangers, each hosting microbes that probably enjoy the moist, pleasant surfaces of the bathroom sink.

Isn't it better to enter and leave the public restroom without touching anything other than yourself?

If you _do_ wash your hands in the restroom, what's the best way to dry your hands afterwards? The short answer: [paper towel](http://conversableeconomist.blogspot.ca/2012/12/paper-towels-v-air-dryers.html). 


*How to wash food in the kitchen*



*The dangers of kitchen sponges*



*Microbes and cooking*

Few microbes that inhabit human bodies are able to survive long at temperatures over 165 degrees (F). 



